[server][ConfigManager] Fix build error on CentOS 6
GLib on CentOS 6 is 2.12. It doesn't have
`g_key_file_unref()`. `g_key_file_unref()` is available since 2.32.

See also: https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html#g-key-file-unref

This change fixes the following build error:

    ConfigManager.cc:151: error: 'g_key_file_unref' was not declared in this scope