[server][testArmBase] Fix a build error of clang 3.4
clang 3.4 causes a build error with the following message.

  CXXLD  ActionTp
  testArmBase.cc:212:25: error: cannot create a non-constant pointer to member