[client] Add a setup procedure to install python 1.5 on Ubuntu 12.04.
Previously 'make' on a client directory fails with the following
message due to the django version 1.3.

ValueError: Unable to configure filter 'require_debug_false': Cannot resolve 'django.utils.log.RequireDebugFalse': No module named RequireDebugFalse