[HatoholException] Make it easy to understand the reason of an build error.
For example, the follwoing error message is shown when the exp != val.

HatoholException.h: In instantiation of 'T _buildExpect(T) [with T = long unsigned int; bool COND = false]':
DBClientConfig.cc:116:3:   required from here
HatoholException.h:92:2: error: invalid use of incomplete type 'struct _BuildError'
  _BuildError("The used value is invalid (unexpected) or the matched specialized template method is not defined.");
  ^
HatoholException.h:87:8: error: forward declaration of 'struct _BuildError'
 struct _BuildError; // The body is not defined to cause an build error