Fix a problem that make a test fail. (#1892)
A test for hap (StandardHapTestee.test_normal_run)
  sometimes failed with the following error.

AssertionError: 'None' != '1 http://example.com:80 0 exampleName Admin examplePass 30 10 exampleExtraInfo'

The root cause is that test code runs
an unexpected path by receiving SIGCHILD due to the exit of
a child process created in a previous test.