[server][DBAgent] Change a const reference to a const pointer to avoid a build error.
The definition on a global IndexDef instance that refers a global
TableProfile instance causes the following error.

DBClientHatohol.cc:643:1: error: uninitialized const member 'DBAgent::IndexDef::tableProfile'